### PR TITLE
Read cutoff for 2B and 3B from xml

### PR DESCRIPTION
**Pull request by zonca**
Addresses the 3 body issue in #110

### CODE REVIEW

**Comment by zonca** [comment]
completed the implementation, it gets 3865 for cluster, which is as expected, see #112

however for PBC it gets:
6616
my compuation with `mdtraj` gets 5533

**Comment by agoetz** [comment]
Looked at the code again - I think you must have duplicates, not missing triplets. Can you check your neighborList for replicate triplets?

I thought your loops implied I<J<K but this is not the case. But there is no such restriction. Thus if we have atoms 
1-2-3
i.e. 1-2 within cut and 2-3 within cut the algorithm will find
I=1, J=2 as neighbor of 1, K=3 as neighbor of 2
=> I-J-K
but also
I=3, J=2 as neighbor of 3, K=1 as neighbor of 2
K-J-I

**Comment by zonca** [comment]
following your discussion let's give an example where K is close enough to I but not to J.

Like:
`K-I-J`
In this case the triplet would be missed because we look at `I`'s neighbors and we don't find the `K` atom there.

However `nearbyAtoms` includes all the atoms within distance, so the index of the K atom would have been already in the possible values for J.

Unless `K > I`, but  then `I` will appear in the `nearbyAtoms` list of `K`.

**Comment by zonca** [comment]
ok, tests are passing, there was something wrong in equilibration

**Pull request merged**
