### PR TITLE
Improve install instructions

### PR DESCRIPTION
**Pull request by zonca**
thanks @chemphys for feeback,
any other suggestion or feedback on this changes?

### CODE REVIEW

**Comment by chemphys** [comment]
Now is totally clear. Let me see why I cannot install openMM, and I will check the source code installation.
________________________________________
De: Andrea Zonca [notifications@github.com]
Enviado: viernes, 12 de junio de 2015 13:56
Para: paesanilab/mbpol_openmm_plugin
CC: Marc Riera Riambau
Asunto: [mbpol_openmm_plugin] Improve install instructions (#62)

thanks @chemphys<https://github.com/chemphys> for feeback,
any other suggestion or feedback on this changes?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/paesanilab/mbpol_openmm_plugin/pull/62

Commit Summary

  *   Update INSTALL.md

File Changes

  *   M INSTALL.md<https://github.com/paesanilab/mbpol_openmm_plugin/pull/62/files#diff-0> (20)

Patch Links:

  *   https://github.com/paesanilab/mbpol_openmm_plugin/pull/62.patch
  *   https://github.com/paesanilab/mbpol_openmm_plugin/pull/62.diff

�

**Comment by zonca** [comment]
ok, easier is if you install OpenMM with precompiled binaries

**Comment by chemphys** [comment]
Some more feedback:

6. Set:
--a-- OPENMM_BUILD_MBPOL_CUDA_LIB OFF (not supported yet) --> It is not in the options


Run make PythonInstall to install the Python wrapper, it requires Python and swig, the best is to use the Anaconda Python distribution
---> It doesn't work:

/home/mriera/codes/build_mbpol# make PythonInstall
make: *** No rule to make target `PythonInstall'.  Stop.

Until this step, everything looks to work well. What is happening?

Thanks!

**Comment by zonca** [comment]
Have you set in the options that you want to build the python wrapper?

**Comment by zonca** [comment]
When you run cmake

**Comment by chemphys** [comment]
Nope. I think it would be a good idea to put it in the instructions. Like : if you want to do the python wrapper, set this option ON.
Also, it would be a good idea to specify how to install swig (like sudo ap-get install swig), and a comment about what's that. 

Everything else is clear. If you need me to test more things, do not hesitate to ask!

See ya!

Marc

**Comment by chemphys** [comment]
The results of the test:

mriera@ockham: build_mbpol]$ make test
Running tests...
Test project /home/mriera/codes/build_mbpol
      Start  1: TestReferenceMBPolIntegrationTestWater50PME
 1/10 Test  #1: TestReferenceMBPolIntegrationTestWater50PME ...   Passed    4.70 sec
      Start  2: TestReferenceMBPolElectrostaticsForce
 2/10 Test  #2: TestReferenceMBPolElectrostaticsForce .........   Passed    1.93 sec
      Start  3: TestReferenceMBPolOneBodyForce
 3/10 Test  #3: TestReferenceMBPolOneBodyForce ................   Passed    0.00 sec
      Start  4: TestReferenceMBPolTwoBodyForce
 4/10 Test  #4: TestReferenceMBPolTwoBodyForce ................   Passed    0.00 sec
      Start  5: TestReferenceMBPolThreeBodyForce
 5/10 Test  #5: TestReferenceMBPolThreeBodyForce ..............   Passed    0.00 sec
      Start  6: TestReferenceMBPolIntegrationTest
 6/10 Test  #6: TestReferenceMBPolIntegrationTest .............   Passed  110.28 sec
      Start  7: TestReferenceMBPol14WaterTest
 7/10 Test  #7: TestReferenceMBPol14WaterTest .................   Passed    0.18 sec
      Start  8: TestReferenceThreeNeighborList
 8/10 Test  #8: TestReferenceThreeNeighborList ................   Passed    0.00 sec
      Start  9: TestReferenceMBPolDispersionForce
 9/10 Test  #9: TestReferenceMBPolDispersionForce .............   Passed    0.00 sec
      Start 10: TestReferenceMBPolIntegrationTestWater3
10/10 Test #10: TestReferenceMBPolIntegrationTestWater3 .......   Passed    0.95 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) = 118.07 sec

**Comment by zonca** [comment]
thanks @chemphys I fixed that in the install instructions!

**Pull request merged**
