### PR TITLE
Implementation of two body force for Cl

### PR DESCRIPTION
**Pull request by sqamara**
TODO:

* [x] fix travis
* [x] implement and test imageMolecules with an ion
* [x] adjust calculatePairIxn to identify which site is an ion and not depend on the ion being at siteI
* [x] make test case for two water and one ion

### CODE REVIEW

**Comment by sqamara** [comment]
TODO:

* [ ] fix travis
* [ ] implement and test imageMolecules with an ion
* [ ] adjust calculatePairIxn to identify which site is an ion and not depend on the ion being at siteI

**Comment by sqamara** [comment]
@zonca I Finished working on the two body force for ions but I am getting confused working with git and rebasing the commits.  I edited my commits but then they were only added on top of my original commits.

**Comment by zonca** [comment]
you don't have to merge the branch back to this branch.

you need to close this pull request (we keep it for the records) and then reopen another pull request (against the `ions` branch) with that other branch (you can call it, `chloride_two_body_clean`).

Make sure you reference this Pull Request from the new one.

**Comment by sqamara** [comment]
Closing this pull request. Link to cleaned version https://github.com/paesanilab/mbpol_openmm_plugin/pull/76

**Pull request closed without merging**
