### PR TITLE
WIP Implementing dispersion force in xml

### PR DESCRIPTION
**Pull request by sqamara**
TODO:

* [x] fix travis
* [x] update dispersion parameters, see #69 
* [x] remove references to the dispersion force in cpp
* [x] clean up history
* [x] make new branch and pull request when it is all clean

### CODE REVIEW

**Comment by sqamara** [comment]
@zonca I uploaded `TestReferenceMbPolIntegrationTest.py` which has all four integration test within it.  The failure is being caused in `test_water256_periodic()'. There is an Ipython notebook that I have been using to try to understand the error, `water256_integration_test_debug.ipynb`

**Comment by zonca** [comment]
@sqamara can you modify this Pull Request to merge into the `ions` branch? I am using that branch for developing support for ions. If not, when you are ready for cleaning up the commits, you can close this PR and open another that points to `ions`.

**Comment by sqamara** [comment]
@zonca Could you clarify what I should do to remove references to the dispersion force in cpp?  Should I remove the MBPolReferenceDispersionForce.cpp and header and any reference to them such as in MBPolReferenceDispersionForce.cpp? do I need to replace the code in the kernels to use the custom dispersion force?

**Comment by zonca** [comment]
@sqamara exactly, remove everything referencing MBPolDispersionForce, not only MBPolReferenceDispersionForce.

the code in the kernels can be removed completely, basically DispersionForce is not anymore a part of the OpenMM MBPol plugin. It lives only in the xml.

The only open issue is the integration tests, we need to:

- [ ] make sure all Integration tests (we have some with different number of water molecules) are all available also in Python
- [ ] find a solution for the C++ integration tests. I would like those tests to be available. for this I think the only solution is: 1) create a .cpp file where you create a DispersionForce using CustomNonbonbded (copying most of the code from the xml) 2) include this file just in the integration tests. Let me know if you think this is feasible or if you have another proposal.

**Comment by zonca** [comment]
@sqamara added another element to the todo list

**Comment by sqamara** [comment]
@zonca I've removed all references of the MBPolDispersionForce and MBPolReferenceDispersionForce, however the project no longer builds because `make[2]: *** No rule to make target '/home/sebastian/mbpol_openmm_plugin/openmmapi/src/MBPolDispersionForce.cpp', needed by 'CMakeFiles/OpenMMMBPol.dir/openmmapi/src/MBPolDispersionForce.cpp.o'.  Stop.`

**Comment by zonca** [comment]
@sqamara great, it is probably due to the cache in CMake that still references that file.
Can you try to create the `build_mbpol` folder again and rerun `ccmake`?

**Comment by sqamara** [comment]
@zonca I tried to remake the CMake (which worked while I was working on the three body force) but i still am getting an error when I make to compile the C++ library.  I get the following error
`../libOpenMMMBPolReference.so: undefined reference to `MBPolPlugin::ReferenceCalcMBPolDispersionForceKernel::ReferenceCalcMBPolDispersionForceKernel(std::string, OpenMM::Platform const&, OpenMM::System const&)'
collect2: error: ld returned 1 exit status
platforms/reference/tests/CMakeFiles/TestReferenceMBPol14WaterTest.dir/build.make:87: recipe for target 'platforms/reference/tests/TestReferenceMBPol14WaterTest' failed
make[2]: *** [platforms/reference/tests/TestReferenceMBPol14WaterTest] Error 1
CMakeFiles/Makefile2:179: recipe for target 'platforms/reference/tests/CMakeFiles/TestReferenceMBPol14WaterTest.dir/all' failed
make[1]: *** [platforms/reference/tests/CMakeFiles/TestReferenceMBPol14WaterTest.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by zonca** [comment]
ok, can you check that you also removed any reference to the `ReferenceCalcMBPolDispersionForceKernel`?

**Comment by sqamara** [comment]
Closing pull request, cleaned version https://github.com/paesanilab/mbpol_openmm_plugin/pull/78

**Pull request closed without merging**
