### PR TITLE
[WIP] Implement Python tests

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
Electrostatics test with virtual sites works fine.

The problem is if I try to run with no virtual sites, huge energy error, I think it is an issue in the parsing of the XML, needs more debugging

- [ ] fix electrostatics test with no virtual sites

**Comment by zonca** [comment]
@pushpbajaj I've implemented this integration test, I get `-66.36 Kcal/mol` for the total energy instead.

I made several cross-checks and everything looks fine, could you please review your simulation just to make sure there are no errors there?

**Comment by pushpbajaj** [comment]
@zonca I checked the calculation again, I get the same result.

The total energy is -45.5367 kcal/mol (Einteraction + E1tot) which actually makes sense because the energy from ab initio calculation for the same configuration is -45.97 kcal/mol.

Did you do a decomposition of the energy into the electrostatics and monomer energy and 2B and 3B energies, etc. to see where the difference is coming from?

**Comment by zonca** [comment]
thanks @pushpbajaj , this is very helpful, I will debug each term independently and see what is the problem.

**Comment by zonca** [comment]
got it!

`-45.4569865550067 kcal/mol`
the Python wrapper was not including Cl in the 2 and 3 body forces

**Comment by zonca** [comment]
@sqamara for some reason C++ tests are now failing in this branch.

can you take a look?

```
zonca@spinoza:~/Paesani/OpenMM/openmm/plugins/build_mbpol$ make test
Running tests...
Test project /home/zonca/Paesani/OpenMM/openmm/plugins/build_mbpol
    Start 1: TestReferenceMBPolElectrostaticsForce
1/6 Test #1: TestReferenceMBPolElectrostaticsForce ...........   Passed    2.14 sec
    Start 2: TestReferenceMBPolOneBodyForce
2/6 Test #2: TestReferenceMBPolOneBodyForce ..................***Failed    0.01 sec
    Start 3: TestReferenceMBPolTwoBodyForce
3/6 Test #3: TestReferenceMBPolTwoBodyForce ..................   Passed    0.01 sec
    Start 4: TestReferenceMBPolElectrostaticsForceChloride
4/6 Test #4: TestReferenceMBPolElectrostaticsForceChloride ...***Failed    0.00 sec
    Start 5: TestReferenceThreeNeighborList
5/6 Test #5: TestReferenceThreeNeighborList ..................   Passed    0.00 sec
    Start 6: TestReferenceMBPolThreeBodyForce
6/6 Test #6: TestReferenceMBPolThreeBodyForce ................***Failed    0.00 sec

50% tests passed, 3 tests failed out of 6

Total Test time (real) =   2.17 sec

The following tests FAILED:
          2 - TestReferenceMBPolOneBodyForce (Failed)
          4 - TestReferenceMBPolElectrostaticsForceChloride (Failed)
          6 - TestReferenceMBPolThreeBodyForce (Failed)
Errors while running CTest
make: *** [test] Error 8
```

error is:

```
zonca@spinoza:~/Paesani/OpenMM/openmm/plugins/build_mbpol$ ./platforms/reference/tests/TestReferenceMBPolOneBodyForce
TestReferenceMBPolOneBodyForce running test...
exception: Specified a Platform for a Context which does not support all required kernels
FAIL - ERROR.  Test failed.
```

**Comment by zonca** [comment]
See #105

**Pull request closed without merging**
