### PR TITLE
[WIP] Cuda electrostatics

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
Implementing `getAndScaleInverseRs` trying to avoid branching as much as possible

**Comment by zonca** [comment]
need to port the gamma function calculations to CUDA to use them to get the scaling factors

**Comment by sqamara** [comment]
implemented gammq here https://gist.github.com/sqamara/ca5a5af7e6da992e7e94

**Comment by zonca** [comment]
thanks @sqamara 

I'm still working on the induced dipoles computation, they just need interaction order 3, so no need for gammq yet. Testing `testWater3` of CUDA and Reference, get a wrong dipole.

```
Reference [0.00371143, -0.000421414, 0.0156151]
CUDA [-0.0104582, 0.0207791, -0.0293226]
```

need to debug `multipoleFixedField.cu`

**Comment by zonca** [comment]
now CUDA gets the correct fixed field.

**Comment by zonca** [comment]
working on induced dipoles,
in Reference I get:

```
[0.00217449, -0.00112286, 0.00554906]
[0.000858875, -0.00014489, 0.000259443]
```

in CUDA I get:

```
[0.00177166, -0.00180514, 0.00539973]
[0.000763226, -0.000315948, 0.000381193]
```

which is the same as the fixed field multiplied by polarity, like CUDA is not performing any iteration.

**Comment by zonca** [comment]
restored DIIS dipole convergence code, now induced dipoles are fine.

**Comment by zonca** [comment]
good job @sqamara, I have integrated and tested `gammq` in Electrostatics, it works fine!
The code should probably be optimized, opened an issue to keep track of that #89

**Comment by zonca** [comment]
forces work. need to implement charge redistribution and PME.

**Comment by zonca** [comment]
Completed forces with PME, no charge redistribution, box of 1.8nm:

## Reference

```
Energy: -7.16939 Kcal/mol 
Forces:
Force atom 0: [-3.16044, 2.51619, -10.4468] Kcal/mol/A <openmm-mbpol>
Force atom 1: [2.8369, -1.09973, 1.51442] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-0.000995658, -0.489109, 2.45613] Kcal/mol/A <openmm-mbpol>
Force atom 3: [1.74561, 4.04209, -3.25936] Kcal/mol/A <openmm-mbpol>
Force atom 4: [0.228276, 0.671561, 8.83775] Kcal/mol/A <openmm-mbpol>
Force atom 5: [-0.151251, -0.370903, 0.828224] Kcal/mol/A <openmm-mbpol>
Force atom 6: [2.93059, 4.45924, 1.57344] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-2.60135, -4.48994, -0.199221] Kcal/mol/A <openmm-mbpol>
Force atom 8: [-1.82625, -5.23961, -1.30325] Kcal/mol/A <openmm-mbpol>
```

## CUDA
```
Energy: -7.16939 Kcal/mol 
Forces:
Force atom 0: [-3.16044, 2.51619, -10.4468] Kcal/mol/A <openmm-mbpol>
Force atom 1: [2.8369, -1.09973, 1.51442] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-0.000995709, -0.489109, 2.45613] Kcal/mol/A <openmm-mbpol>
Force atom 3: [1.74561, 4.04209, -3.25936] Kcal/mol/A <openmm-mbpol>
Force atom 4: [0.228276, 0.671561, 8.83775] Kcal/mol/A <openmm-mbpol>
Force atom 5: [-0.151251, -0.370903, 0.828224] Kcal/mol/A <openmm-mbpol>
Force atom 6: [2.93059, 4.45924, 1.57344] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-2.60135, -4.48994, -0.199221] Kcal/mol/A <openmm-mbpol>
Force atom 8: [-1.82625, -5.23961, -1.30325] Kcal/mol/A <openmm-mbpol>
```

**Comment by zonca** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GCgrpl6Z&#x2F;21-cuda-electrostatics"> CUDA electrostatics</a>

**Comment by zonca** [comment]
Completed charge redistribution cluster. Only missing is charge redistribution PME.

**Comment by zonca** [comment]
work completed, now cleaning up before merging, see #96

**Pull request closed without merging**
