### PR TITLE
[WIP] Python tests

### PR DESCRIPTION
**Pull request by sqamara**
Working on reference tests.  In Electrostatics Force, system has no means of setting the charge redistribution, therefore tests cannot match cpp tests.  Ideas for work around: repurpose an unused function of the force class to set the charge redistribution, have option in xml for user to specify.

### CODE REVIEW

**Comment by zonca** [comment]
the relevant commits for this pull requests are from 209daeb onwards

**Comment by sqamara** [comment]
@zonca I was able to set up a way to set the charge redistribution from the xml file.  However the python reference electrostatics test still fails.  The expected energy and forces are all incorrect.  I am having trouble finding what is causing the difference between the cpp and python tests.

**Comment by zonca** [comment]
@sqamara can you paste here the difference?

would it be possible that it is just the difference precision in the input coordinates? i.e. pdb file only have 3 or 4 digits.

**Comment by sqamara** [comment]
I do not think it is because of the difference in input coordinates.  the results are
energy = -7.095074450433603 kcal/mol
Forces: 
(-3.1926457087433158, 2.4269320600553472, -10.388647968506826) Kcal/mol/A

(2.8561765765117872, -1.0581429413298884, 1.4860413687116527) Kcal/mol/A

(0.015673477349190557, -0.4508908033036091, 2.4255131031743025) Kcal/mol/A

(0.0, 0.0, 0.0) Kcal/mol/A

(1.7093727295193313, 3.9649495595807682, -3.1855956018005065) Kcal/mol/A

(0.239216466298758, 0.7055451759488467, 8.802527395588829) Kcal/mol/A

(-0.13264896589055936, -0.3352510973956325, 0.7918512245954168) Kcal/mol/A

(0.0, 0.0, 0.0) Kcal/mol/A

(2.8846439520587324, 4.37627214452168, 1.6338908177946907) Kcal/mol/A

(-2.57412320007399, -4.43149472225196, -0.2332807043804698) Kcal/mol/A

(-1.8056653270299359, -5.1979193758255535, -1.3322996351770873) Kcal/mol/A

(0.0, 0.0, 0.0) Kcal/mol/A

and the expected are
energy =-19.6545 Kcal/mol 
Forces:
[-5.53127, 1.42697, -26.8317] Kcal/mol/A 

[5.00427, -1.62032, 5.9788] Kcal/mol/A 

[-0.304354, -0.551834, 6.1784] Kcal/mol/A 

[6.07087, 16.3677, 7.41079] Kcal/mol/A 

[-1.38257, -3.3467, 10.5548] Kcal/mol/A 

[-1.02774, -2.34605, 0.300803] Kcal/mol/A 

[3.04715, 3.39407, -1.12422] Kcal/mol/A 

[-3.13591, -5.75858, -1.368] Kcal/mol/A 

[-2.74044, -7.56528, -1.0997] Kcal/mol/A

**Comment by zonca** [comment]
Continues in #82 

@sqamara when you set no charge redistribution, you also need to remove the virtual sites from the pdb. Testing that in #82

**Pull request closed without merging**
