### PR TITLE
Implementing dispersion force in xml

### PR DESCRIPTION
**Pull request by sqamara**
Cleaned pull request of https://github.com/paesanilab/mbpol_openmm_plugin/pull/67

### CODE REVIEW

**Comment by sqamara** [comment]
@zonca I finished the checklist for Implementing dispersion force in xml.  note that travis does not work

**Comment by zonca** [comment]
@sqamara are your local tests working? it looks like:

    #include "openmm/MBPolDispersionForce.h"

is still present in some files, can you try remove that and check travis?

**Comment by sqamara** [comment]
@zonca The project was building localy.  I found `#include "openmm/MBPolDispersionForce.h"` in two files and in many of the CMake files.  I only removed if from the two.  Travis still does not work.

**Comment by zonca** [comment]
Continues in #80

**Pull request closed without merging**
