### PR TITLE
[WIP] Support ions in MBPol Electrostatics, Reference platform

### PR DESCRIPTION
**Pull request by zonca**
First implementation of #50 

The purpose is to add support for any Ion to the OpenMM-MBPol plugin.

At first I plan on using simplifying assumptions:

* only 1 ion
* last particle in the set

### CODE REVIEW

**Comment by zonca** [comment]
First test case with a cluster of 3 water molecules and 1 Cl, energy passes, forces are correct only on the Chloride, wrong on all water molecules. Any hint on what might be wrong @pushpbajaj @gmedders ?

Is any modification required to the force computation in presence of ions?
See the code:
https://github.com/zonca/mbpol_openmm_plugin/blob/f877250720b43cafb4360f166a96d22e83b8ad8b/platforms/reference/src/MBPolReferenceElectrostaticsForce.cpp#L1197

```
Test START: testWater3VirtualSiteChloride
Energy: -41.1134 Kcal/mol 
Expected energy: -41.1134 Kcal/mol 

Forces:
Force atom 0: [-26.1368, -5.40828, 16.2952] Kcal/mol/A <mbpol>
Force atom 0: [-36.9571, -2.27187, 18.1314] Kcal/mol/A <openmm-mbpol>
Force atom 0: [-26.1368, -5.40827, 16.2952] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [22.1692, 25.9079, -62.9639] Kcal/mol/A <mbpol>
Force atom 1: [29.2488, 22.1781, -60.9225] Kcal/mol/A <openmm-mbpol>
Force atom 1: [22.1692, 25.9079, -62.9639] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [-1.5177, 3.04609, -3.8373] Kcal/mol/A <mbpol>
Force atom 2: [2.223, 3.63955, -7.71484] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-1.5177, 3.04609, -3.8373] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 4: [-16.3635, 4.33611, -19.7297] Kcal/mol/A <mbpol>
Force atom 4: [-18.0418, 3.73288, -26.3243] Kcal/mol/A <openmm-mbpol>
Force atom 4: [-16.3635, 4.3361, -19.7297] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 5: [36.4086, 8.18161, 28.0008] Kcal/mol/A <mbpol>
Force atom 5: [35.3562, 7.44765, 32.5706] Kcal/mol/A <openmm-mbpol>
Force atom 5: [36.4086, 8.18161, 28.0008] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 6: [1.65624, 1.10512, -0.705986] Kcal/mol/A <mbpol>
Force atom 6: [4.38688, 2.4423, 1.31885] Kcal/mol/A <openmm-mbpol>
Force atom 6: [1.65623, 1.10512, -0.705989] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 7: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 7: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 8: [-9.97784, 32.2664, -8.6059] Kcal/mol/A <mbpol>
Force atom 8: [-8.23374, 34.4396, -13.0367] Kcal/mol/A <openmm-mbpol>
Force atom 8: [-9.97784, 32.2664, -8.60591] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 9: [15.3607, -33.4848, -8.22473] Kcal/mol/A <mbpol>
Force atom 9: [13.3193, -35.9114, -5.35407] Kcal/mol/A <openmm-mbpol>
Force atom 9: [15.3607, -33.4848, -8.22473] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 10: [2.03685, -13.2406, 9.84] Kcal/mol/A <mbpol>
Force atom 10: [2.33416, -12.9872, 11.4001] Kcal/mol/A <openmm-mbpol>
Force atom 10: [2.03685, -13.2406, 9.84] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 11: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 11: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 11: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <mbpol>
Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <openmm-mbpol>
Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <openmm-mbpol finite differences>

Comparison of energy and forces with tolerance: 0.0001
```

**Comment by gmedders** [comment]
@zonca, can you try testing to make sure that the forces on just the water molecules is correct (ie, remove the ion from the system, test the forces versus finite differences)? Obviously, this should work, but it could be a good sanity check.

There should be no modification of the force required for MB-pol water relative to MB-pol water/ions. If this doesn't work, I would try disabling the energy/force contributions one by one...

**Comment by zonca** [comment]
Thanks @pushpbajaj for helping to fix the problem.
I had excluded the force redistribution between water atoms and the ion, instead it should be included, see: d5f4f04

Test results:

```cpp
Test START: testWater3VirtualSiteChloride
Energy: -41.1134 Kcal/mol 
Expected energy: -41.1134 Kcal/mol 

Forces:
Force atom 0: [-26.1368, -5.40828, 16.2952] Kcal/mol/A <mbpol>
Force atom 0: [-26.1368, -5.40827, 16.2952] Kcal/mol/A <openmm-mbpol>
Force atom 0: [-26.1368, -5.40827, 16.2952] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [22.1692, 25.9079, -62.9639] Kcal/mol/A <mbpol>
Force atom 1: [22.1692, 25.9079, -62.9639] Kcal/mol/A <openmm-mbpol>
Force atom 1: [22.1692, 25.9079, -62.9639] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [-1.5177, 3.04609, -3.8373] Kcal/mol/A <mbpol>
Force atom 2: [-1.5177, 3.04609, -3.8373] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-1.5177, 3.04609, -3.8373] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 4: [-16.3635, 4.33611, -19.7297] Kcal/mol/A <mbpol>
Force atom 4: [-16.3635, 4.3361, -19.7297] Kcal/mol/A <openmm-mbpol>
Force atom 4: [-16.3635, 4.3361, -19.7297] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 5: [36.4086, 8.18161, 28.0008] Kcal/mol/A <mbpol>
Force atom 5: [36.4086, 8.18161, 28.0008] Kcal/mol/A <openmm-mbpol>
Force atom 5: [36.4086, 8.18161, 28.0008] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 6: [1.65624, 1.10512, -0.705986] Kcal/mol/A <mbpol>
Force atom 6: [1.65624, 1.10512, -0.705987] Kcal/mol/A <openmm-mbpol>
Force atom 6: [1.65623, 1.10512, -0.705989] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 7: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 7: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 8: [-9.97784, 32.2664, -8.6059] Kcal/mol/A <mbpol>
Force atom 8: [-9.97784, 32.2664, -8.6059] Kcal/mol/A <openmm-mbpol>
Force atom 8: [-9.97784, 32.2664, -8.60591] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 9: [15.3607, -33.4848, -8.22473] Kcal/mol/A <mbpol>
Force atom 9: [15.3607, -33.4848, -8.22473] Kcal/mol/A <openmm-mbpol>
Force atom 9: [15.3607, -33.4848, -8.22473] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 10: [2.03685, -13.2406, 9.84] Kcal/mol/A <mbpol>
Force atom 10: [2.03685, -13.2406, 9.84] Kcal/mol/A <openmm-mbpol>
Force atom 10: [2.03685, -13.2406, 9.84] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 11: [-0, -0, -0] Kcal/mol/A <mbpol>
Force atom 11: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 11: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <mbpol>
Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <openmm-mbpol>
Force atom 12: [-23.6357, -22.7096, 49.9315] Kcal/mol/A <openmm-mbpol finite differences>

Comparison of energy and forces with tolerance: 0.0001

Test Successful: testWater3VirtualSiteChloride
```

Next PME

**Comment by zonca** [comment]
@pushpbajaj I am working on the PME version of the code, could you please run this same test case for electrostatics only in a box of 18A?

**Comment by pushpbajaj** [comment]
@zonca following is the electrostatics energy and forces for two configurations from DLPOPLY

Tetramer 1: 
```
O1    -1.516074336        -0.202316765        1.454672917
H1    -0.621898977        -0.600943073        1.572437625
H1    -2.017613812        -0.419035035        2.239642849
O2    -1.763651687        -0.381659465       -1.300353949
H2    -1.903851736        -0.493567762       -0.345781012
H2    -2.527904158        -0.761355008       -1.733803676
O3    -0.558847214         2.006699172       -0.139278658
H3    -0.941155818         1.541226676        0.616329307
H3    -0.985855173         1.567124294       -0.883097094
Cl     0.000000000         0.000000000        0.000000000
``` 

Electrostatics energy = -45.1605 kcal/mol

Forces 
``` 
  1   2.712987790E+01  2.136633812E+01 -4.996446629E+01
  2   1.693801151E+01  6.627253569E+00 -1.334017664E+01
  3  -1.675724529E+01 -2.625447123E+01  6.077429828E+01
  4   2.095542532E+00 -3.147994837E+00  3.543703744E+00
  5   1.340582407E+01 -4.735480609E+00  9.689785282E+00
  6  -3.497445137E+01 -7.738009661E+00 -1.929365002E+01
  7  -6.243128433E-01 -4.689622738E-01  1.130358076E+00
  8   1.076930855E+01 -2.783937908E+01  6.681571182E+00
  9  -1.675261222E+01  3.098935668E+01  9.489048817E+00
 10  -1.229942845E+00  1.120134932E+01 -8.710472429E+00
```

Tetramer 2: 
``` 
 O1         -0.1197230468       -1.9834287501       -0.5424945834
 H1         -0.3825671147       -1.3505641998       -1.2268433231
 H1         -0.6898178940       -1.6763362331        0.1907649021
 O2         -1.6646953442        0.3046493203       -1.7023293335
 H2         -1.7091992012        0.3269545676       -0.7151426044
 H2         -2.5014788166       -0.1140091294       -1.9241376202
 O3          1.3844695571       -0.1653094101        1.3563851856
 H3          0.4561093953        0.0478083854        1.5596472046
 H3          1.2582498773       -0.8113040851        0.6473022979
 Cl         -1.8804887171       -0.1220932519        1.3514717294
``` 

Electrostatics energy = -61.0001 kcal/mol

Forces: 
```
  1  -1.919056331E+01  4.891772560E+00  2.852201486E+01
  2  -1.019346998E+01  2.034130817E+00  4.972265449E+00
  3   4.446650580E+00 -5.601508095E+00 -3.032382065E+00
  4   1.354538764E+01 -1.671545994E+01 -1.156351985E+01
  5   3.115154121E+00  7.742765917E+00  7.983855464E+00
  6  -4.084699247E-01  6.098679489E+00 -2.964771575E+01
  7  -6.372372939E+00 -2.686092813E+00 -2.712546493E+00
  8  -7.487329210E+00 -1.013718961E-02 -1.732096289E+00
  9   1.502489308E+01  2.143707217E+00  4.525107431E+00
 10   7.520119946E+00  2.102142037E+00  2.685017237E+00
```

**Comment by zonca** [comment]
@pushpbajaj can you please run also the usual water 3 configuration with the Cl- ion in (2,0,0)? so we always use the same system

**Comment by pushpbajaj** [comment]
@zonca 

Tetramer:
```
O1    -1.516074336        -0.202316765        1.454672917
H1    -0.621898977        -0.600943073        1.572437625
H1    -2.017613812        -0.419035035        2.239642849
O2    -1.763651687        -0.381659465       -1.300353949
H2    -1.903851736        -0.493567762       -0.345781012
H2    -2.527904158        -0.761355008       -1.733803676
O3    -0.558847214         2.006699172       -0.139278658
H3    -0.941155818         1.541226676        0.616329307
H3    -0.985855173         1.567124294       -0.883097094
Cl     2.000000000         0.000000000        0.000000000
```

Electrostatics energy = -13.5382 kcal/mol

Forces:
```
  1   3.378177582E+00  6.577586284E+00 -7.637656903E+00
  2   7.881946623E+00  3.893803383E+00  3.146957401E+00
  3  -1.377059330E+01 -4.986522593E+00  1.187458351E+01
  4   1.766750640E-01 -3.173283815E+00  4.373651728E+00
  5   9.379890659E+00 -2.244573906E+00  5.082518827E+00
  6  -8.662806336E+00 -4.819314700E+00 -1.625949209E+01
  7  -2.988611811E+00 -1.082696042E+00  7.181995028E-02
  8   1.001822831E+01 -1.405075505E+01 -1.429225734E+00
  9  -2.602893373E+00  8.771839231E+00  1.836003914E+00
 10  -2.810013423E+00  1.111391721E+01 -1.059160598E+00
```

**Comment by zonca** [comment]
Good, thanks, here are OpenMM-MBPol results

```
Energy: -13.4724 Kcal/mol 

Force atom 0: [-13.5202, -2.1198, -3.57256] Kcal/mol/A <openmm-mbpol>
Force atom 0: [-13.5221, -2.12167, -3.5848] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [18.782, 3.59001, -11.5919] Kcal/mol/A <openmm-mbpol>
Force atom 1: [18.7817, 3.59001, -11.592] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [-0.0797143, 3.0704, -4.39667] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-0.079764, 3.07032, -4.39644] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 4: [-9.95268, 2.38737, -7.39132] Kcal/mol/A <openmm-mbpol>
Force atom 4: [-9.9527, 2.38737, -7.39074] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 5: [9.19016, 5.00807, 18.8242] Kcal/mol/A <openmm-mbpol>
Force atom 5: [9.19241, 5.01003, 18.8356] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 6: [3.27407, 1.22799, -0.103198] Kcal/mol/A <openmm-mbpol>
Force atom 6: [3.27407, 1.228, -0.103192] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 7: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>
  
Force atom 8: [-9.97884, 14.3857, 1.29876] Kcal/mol/A <openmm-mbpol>
Force atom 8: [-9.97872, 14.3853, 1.29869] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 9: [2.50154, -9.47547, -1.81739] Kcal/mol/A <openmm-mbpol>
Force atom 9: [2.50169, -9.47539, -1.8169] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 10: [2.87964, -11.3632, 1.09656] Kcal/mol/A <openmm-mbpol>
Force atom 10: [2.8797, -11.3631, 1.09643] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 11: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 11: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 12: [-3.09597, -6.7111, 7.65351] Kcal/mol/A <openmm-mbpol>
Force atom 12: [-3.09631, -6.71087, 7.65339] Kcal/mol/A <openmm-mbpol finite differences>
```

@pushpbajaj what are the units on your forces?

**Comment by pushpbajaj** [comment]
The units are kcal/mol/A and I'm printing the derivatives.

**Comment by zonca** [comment]
@pushpbajaj I ran the other configuration with positions:

```
 O1         -0.1197230468       -1.9834287501       -0.5424945834
 H1         -0.3825671147       -1.3505641998       -1.2268433231
 H1         -0.6898178940       -1.6763362331        0.1907649021
 O2         -1.6646953442        0.3046493203       -1.7023293335
 H2         -1.7091992012        0.3269545676       -0.7151426044
 H2         -2.5014788166       -0.1140091294       -1.9241376202
 O3          1.3844695571       -0.1653094101        1.3563851856
 H3          0.4561093953        0.0478083854        1.5596472046
 H3          1.2582498773       -0.8113040851        0.6473022979
 Cl         -1.8804887171       -0.1220932519        1.3514717294
```

the output is:

```
Energy: -60.6884 Kcal/mol 

Force atom 0: [10.6613, -2.66577, -4.03061] Kcal/mol/A <openmm-mbpol>
Force atom 0: [10.6648, -2.66793, -4.04421] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [-5.26723, 6.32927, 2.18636] Kcal/mol/A <openmm-mbpol>
Force atom 1: [-5.25837, 6.32097, 2.1766] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [-12.9798, 16.2956, 11.3588] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-13.0073, 16.3268, 11.3992] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 4: [-2.26997, -7.99818, -16.0098] Kcal/mol/A <openmm-mbpol>
Force atom 4: [-2.27803, -7.99582, -15.9938] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 5: [-0.285216, -5.50403, 37.7154] Kcal/mol/A <openmm-mbpol>
Force atom 5: [-0.308597, -5.60481, 38.1251] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 6: [6.2457, 2.58422, 2.54908] Kcal/mol/A <openmm-mbpol>
Force atom 6: [6.24553, 2.58558, 2.53282] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 7: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 7: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 8: [10.6703, -0.316524, 1.39659] Kcal/mol/A <openmm-mbpol>
Force atom 8: [10.6735, -0.3146, 1.38666] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 9: [-17.9791, -1.97802, -4.42191] Kcal/mol/A <openmm-mbpol>
Force atom 9: [-17.995, -1.98215, -4.4083] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 10: [-7.85781, -2.10228, -2.55624] Kcal/mol/A <openmm-mbpol>
Force atom 10: [-7.85149, -2.10366, -2.55425] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 11: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 11: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 12: [19.0619, -4.64426, -28.1877] Kcal/mol/A <openmm-mbpol>
Force atom 12: [19.1149, -4.5644, -28.6198] Kcal/mol/A <openmm-mbpol finite differences>
```

**Comment by zonca** [comment]
@pushpbajaj it is useful if you try with finite differences before I merge this into the master branch.

**Comment by pushpbajaj** [comment]
water trimer : 

```
O1    -1.516074336        -0.202316765        1.4546729170
H1    -0.621898977        -0.600943073        1.572437625
H2    -2.017613812        -0.419035035        2.239642849
O2    -1.763651687        -0.381659465        -1.300353949
H2    -1.903851736        -0.493567762        -0.345781012
H2    -2.527904158        -0.761355008        -1.733803676
O3    -0.558847214         2.006699172        -0.139278658
H3    -0.941155818         1.541226676         0.616329307
H3    -0.985855173         1.567124294        -0.8830970941
```

electrostatics energy =  -15.8188491183429

 ```
  1   1.566846677E+00  5.919196479E+00 -1.596092322E+01
  2  -4.098458608E+00  8.304266337E-01  4.330547262E-01
  3   2.016222344E+00 -6.539256263E-01 -6.029602028E-01
  4   5.514407438E+00  4.971508037E+00  1.194369562E+01
  5   1.597109471E+00  1.664128673E+00 -8.109791273E-01
  6  -1.446897588E+00 -7.842666674E-01  2.532891755E+00
  7  -6.315512072E+00 -1.141321665E+01 -1.589512175E+00
  8   8.647813727E-01 -3.088603397E+00  3.796735879E+00
  9   3.015009656E-01  2.554752520E+00  2.579967399E-01
```

**Comment by pushpbajaj** [comment]
@zonca could you please post the electrostatics energy and forces for the water trimer here from openMM?

**Comment by zonca** [comment]
I moved tests on water to #65 , let's keep this pull requests for Chloride only.

**Pull request merged**
